# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19 is version 41

loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/SeafoamWolf/SeafoamsDyeableBlocks/issues"
showAsResourcePack=false

[[mods]]
  modId="seafoamsdyeableblocks"
  version="1.0.0"
  displayName="Seafoam's Dyeable Blocks"
  logoFile="logo.png"
  authors="SeafoamWolf"
  description='''
  A cosmetic mod adding in multiple dyeable blocks for decoration and pixel art.
  '''

  [[dependencies.seafoamsdyeableblocks]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.seafoamsdyeableblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"