# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/SeafoamWolf/SeafoamsDyeableBlocks/issues"
showAsResourcePack=false

[[mods]]
  modId="seafoamsdyeableblocks"
  version="1.3.2"
  displayName="Seafoam's Dyeable Blocks"
  logoFile="logo.png"
  authors="SeafoamWolf"
  description='''
  Adds full RGB dye support to some blocks for decoration or art! A pixel artist's dream! Works great for Vanilla+!
  '''

  [[dependencies.seafoamsdyeableblocks]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.seafoamsdyeableblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"